#!/usr/bin/env bash


DEFSHELL=$(grep "^$USER" /etc/passwd | sed 's/.*bin\///')

if [ $DEFSHELL = 'zsh' ]; then
    echo alias cavdev="\"(cd $(pwd) && vagrant up && vagrant ssh; vagrant halt)\"" >> ~/.zshrc 
    echo -e "\e[33mReopen terminal or run\n"


echo -e "\e[32msource ~/.zshrc\n"


else
    echo alias cavdev="\"(cd $(pwd) && vagrant up && vagrant ssh; vagrant halt)\"" >> ~/.bashrc && source ~/.zshrc
    echo -e "\e[33mReopen terminal or run\n"

echo -e "\e[32msource ~/.bashrc\n"

fi
    echo -e "\e[33mto add to bash profile, then\n"

echo -e "\e[32mcavdev\n"

echo -e "\e[33mto run the vagrant"
